default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
development:
  <<: *default
  database: slidebox_development
test:
  <<: *default
  database: slidebox_test
production:
  <<: *default
  database: slidebox_production
  username: cone
  password: <%= ENV['SPHYNX_DATABASE_PASSWORD'] %>
